version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: university
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Admin1234*
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./services/db/config/init.sql:/docker-entrypoint-initdb.d/init.sql

  app:
    build: .
    environment:
      DB_USER: postgres
      DB_PASSWORD: Admin1234*
      DB_NAME: university
      DB_HOST: db
      DB_PORT: 5432
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    depends_on:
      - db

  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: test@test.com  # Replace with your email
      PGADMIN_DEFAULT_PASSWORD: 123456        # Replace with your password
    ports:
      - "5001:80"
    depends_on:
      - db

volumes:
  pg_data:
